name: "Nix"
on:
  push:
    branches:
      - mara
  pull_request:
    branches:
      - mara
jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v12
      - uses: cachix/cachix-action@v7
        with:
          name: xe
      - run: |
          nix-build
